#ifndef INC_APP_UTIL_H_
#define INC_APP_UTIL_H_

#define BOOTLOADER_UPDATER_RX_BUFFER_LENGTH     100000


#define BOOTLOADER_UPDATER_MAJOR_VERSION 7
#define BOOTLOADER_UPDATER_MINOR_VERSION 2
#define BOOTLOADER_UPDATER_PATCH_VERSION 9

#define BOOTLOADER_START_ADDRESS 0x08040000
#define BOOTLOADER_BINARY_START_ADDRESS BOOTLOADER_START_ADDRESS

#define APP_ENTER 0
#define BOOTLOADER_ENTER 1

void Bootloader_Updater_Receive_Command(void);

#endif /* INC_APP_UTIL_H_ */
