
#ifndef INC_APP_UTIL_H_
#define INC_APP_UTIL_H_

#include "stm32f4xx_hal.h"

#define BOOTLOADER_RX_BUFFER_LENGTH     100000


#define BOOTLOADER_MAJOR_VERSION 3
#define BOOTLOADER_MINOR_VERSION 4
#define BOOTLOADER_PATCH_VERSION 5

#define APP_ENTER 0
#define BOOTLOADER_ENTER 1


#define BOOTLOADER_START_ADDRESS 0x08040000
#define BOOTLOADER_BINARY_START_ADDRESS BOOTLOADER_START_ADDRESS

#define APP_START_ADDRESS 0x080A0000
#define APP_NO_OF_BYTES_START_ADDRESS APP_START_ADDRESS
#define APP_Digest_START_ADDRESS (APP_START_ADDRESS + 32)
#define APP_BINARY_START_ADDRESS (APP_START_ADDRESS + 0x200)

#define BOOTLOADER_UPDATER_START_ADDRESS 0x080A0000
#define BOOTLOADER_UPDATER_BINARY_START_ADDRESS BOOTLOADER_UPDATER_START_ADDRESS



void Bootloader_Receive_Command(void);

#endif /* INC_APP_UTIL_H_ */
