#ifndef INC_APP_UTIL_H_
#define INC_APP_UTIL_H_

#define BOOTLOADER_START_ADDRESS 0x08040000
#define BOOTLOADER_BINARY_START_ADDRESS BOOTLOADER_START_ADDRESS

#define APP_ENTER 0
#define BOOTLOADER_ENTER 1

void Update_Logic();

#endif /* INC_APP_UTIL_H_ */
